[profile.default]
src = 'contracts'
out = 'out'
build_info = true
remappings = ["forge-std/=lib/forge-std/src/"]
extra_output = ["storageLayout"]
libs = ['lib']
test = 'test'
cache_path  = 'cache_forge'
solc = "0.8.23"
fs_permissions = [{ access = "read-write", path = "./"}]
